#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 17 12:37:25 2023

@author: lukasgartmair
"""

class MapGenerator():
    
    
    def __init__(self):
        
    def generate_rnd_map():