#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 17 12:39:07 2023

@author: lukasgartmair
"""

NAME = "City Trade"

MODERN_GL = False

SCREEN_WIDTH = 900
SCREEN_HEIGHT= 750
FPS = 30

CAMERA_0_X = 0
CAMERA_0_Y = 0
CAMERA_0_WIDTH = SCREEN_WIDTH
CAMERA_0_HEIGHT = SCREEN_HEIGHT

CAMERA_1_X = 0
CAMERA_1_Y = 0
CAMERA_1_WIDTH = SCREEN_WIDTH
CAMERA_1_HEIGHT = SCREEN_HEIGHT // 2

CAMERA_2_X = 0
CAMERA_2_Y = SCREEN_HEIGHT // 2
CAMERA_2_WIDTH = SCREEN_WIDTH
CAMERA_2_HEIGHT = SCREEN_HEIGHT // 2
